/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sand_management;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.*;
import java.util.*;
import javax.swing.JOptionPane;
/**
 *
 * @author theet
 */
public class employee_new extends javax.swing.JFrame {
    SimpleDateFormat timeFormat;
    SimpleDateFormat dateFormat;
    String time;
    String date;
    private All_Data user;
    /**
     * Creates new form employee_new
     */
    public employee_new(All_Data a1) {
        initComponents();
        this.user = a1;
        Start();
    }
    
    public void Start(){
        setDate();
        setTime();
    }
    
    public void setDate() {
        dateFormat = new SimpleDateFormat("EEEE dd MMMMM yyyy");
        date = dateFormat.format(Calendar.getInstance().getTime());
        jLabelDate.setText(date);
    }
    
    public static String getRandomNumberString() {
        Random rnd = new Random();
        int number = rnd.nextInt(999999);
        return String.format("%06d", number);
    }
    
        public void setTime() {
            timeFormat = new SimpleDateFormat("hh:mm:ss a");
            Timer timer = new Timer();
            TimerTask task = new TimerTask() { // TimerTask is an abstract class .
                @Override
                public void run() {
                    time = timeFormat.format(Calendar.getInstance().getTime());
                    jLabelTime1.setText(time);
                }
            };
            timer.scheduleAtFixedRate(task, 0, 1000);
        }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        checkgroup_family_status = new javax.swing.ButtonGroup();
        checkgroup_service = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabelProgram = new javax.swing.JLabel();
        jLabelTime1 = new javax.swing.JLabel();
        jLabelDate = new javax.swing.JLabel();
        jfirstname_lastname = new javax.swing.JLabel();
        jButtonlogout = new javax.swing.JButton();
        jBack = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        first_name = new javax.swing.JTextField();
        age = new javax.swing.JTextField();
        ethnicity = new javax.swing.JTextField();
        nationality = new javax.swing.JTextField();
        religion = new javax.swing.JTextField();
        birthday = new javax.swing.JTextField();
        id_card = new javax.swing.JTextField();
        current_address = new javax.swing.JTextField();
        district_1 = new javax.swing.JTextField();
        district_2 = new javax.swing.JTextField();
        phone_number = new javax.swing.JTextField();
        province = new javax.swing.JTextField();
        father_name = new javax.swing.JTextField();
        mother_name = new javax.swing.JTextField();
        father_age = new javax.swing.JTextField();
        mother_age = new javax.swing.JTextField();
        father_ethnicity = new javax.swing.JTextField();
        mother_ethnicity = new javax.swing.JTextField();
        father_nationality = new javax.swing.JTextField();
        mother_nationality = new javax.swing.JTextField();
        husband_or_wife_name = new javax.swing.JTextField();
        husband_or_wife_age = new javax.swing.JTextField();
        father_occupation = new javax.swing.JTextField();
        mother_occupation = new javax.swing.JTextField();
        husband_or_wife_ethnicity = new javax.swing.JTextField();
        husband_or_wife_phone = new javax.swing.JTextField();
        husband_or_wife_nationality = new javax.swing.JTextField();
        husband_or_wife_occupation = new javax.swing.JTextField();
        husband_or_wife_workplace = new javax.swing.JTextField();
        husband_or_wife_position = new javax.swing.JTextField();
        education_level = new javax.swing.JTextField();
        name_place_graduated = new javax.swing.JTextField();
        graduated_subject = new javax.swing.JTextField();
        work_history = new javax.swing.JTextField();
        office_name = new javax.swing.JTextField();
        old_position = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        start = new javax.swing.JTextField();
        stop = new javax.swing.JTextField();
        reason_for_resignation = new javax.swing.JTextField();
        reason_for_wanting_to_work_here = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        button_register = new javax.swing.JButton();
        jLabel45 = new javax.swing.JLabel();
        last_name = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        nickname = new javax.swing.JTextField();
        position = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jLabelProgram.setBackground(new java.awt.Color(255, 255, 255));
        jLabelProgram.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        jLabelProgram.setForeground(new java.awt.Color(255, 255, 255));
        jLabelProgram.setText("Employee Registration");

        jLabelTime1.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        jLabelTime1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTime1.setText("Time");

        jLabelDate.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        jLabelDate.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDate.setText("Date");

        jfirstname_lastname.setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        jfirstname_lastname.setForeground(new java.awt.Color(255, 255, 255));
        jfirstname_lastname.setText("User");
        jfirstname_lastname.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jfirstname_lastnameAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jButtonlogout.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jButtonlogout.setForeground(new java.awt.Color(255, 51, 51));
        jButtonlogout.setText("Logout");
        jButtonlogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonlogoutMouseClicked(evt);
            }
        });

        jBack.setFont(new java.awt.Font("Leelawadee UI", 0, 36)); // NOI18N
        jBack.setForeground(new java.awt.Color(255, 255, 255));
        jBack.setText("Back");
        jBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBackMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelTime1)
                        .addGap(30, 30, 30)
                        .addComponent(jLabelDate))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelProgram)
                        .addGap(603, 603, 603)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jfirstname_lastname, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonlogout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(39, 39, 39))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTime1)
                    .addComponent(jLabelDate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelProgram, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBack, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jfirstname_lastname)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonlogout, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 35, Short.MAX_VALUE))))
        );

        jLabel1.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        jLabel1.setText("ชื่อ");

        jLabel2.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        jLabel2.setText("อายุ");

        jLabel3.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        jLabel3.setText("เชื้อชาติ");

        jLabel4.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        jLabel4.setText("สัญชาติ");

        jLabel5.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        jLabel5.setText("ศาสนา");

        jLabel6.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        jLabel6.setText("วัน/เดือน/ปีเกิด");

        jLabel7.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        jLabel7.setText("บัตรประชาชน");

        jLabel8.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        jLabel8.setText("ที่อยู่ปัจจุบัน");

        jLabel9.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        jLabel9.setText("ตำบล");

        jLabel10.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        jLabel10.setText("อำเภอ");

        jLabel11.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        jLabel11.setText("จังหวัด");

        jLabel12.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        jLabel12.setText("เบอร์โทรศัพท์");

        jLabel13.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        jLabel13.setText("ชื่อบิดา");

        jLabel14.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        jLabel14.setText("อายุ");

        jLabel15.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        jLabel15.setText("เชื้อชาติ");

        jLabel16.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        jLabel16.setText("สัญชาติ");

        jLabel17.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        jLabel17.setText("อาชีพ");

        jLabel18.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        jLabel18.setText("ชื่อมารดา");

        jLabel19.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        jLabel19.setText("อายุ");

        jLabel20.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        jLabel20.setText("เชื้อชาติ");

        jLabel21.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        jLabel21.setText("สัญชาติ");

        jLabel22.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        jLabel22.setText("อาชีพ");

        jLabel24.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        jLabel24.setText("สามี/ภรรยา ชื่อ-นามสกุล");

        jLabel25.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        jLabel25.setText("อายุ");

        jLabel26.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        jLabel26.setText("สัญชาติ");

        jLabel27.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        jLabel27.setText("เชื้อชาติ");

        jLabel28.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        jLabel28.setText("อาชีพ");

        jLabel29.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        jLabel29.setText("ที่ทำงาน");

        jLabel30.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        jLabel30.setText("ตำเเหน่ง");

        jLabel31.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        jLabel31.setText("เบอร์โทรศัพท์");

        jLabel33.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        jLabel33.setText("ประวัติการศึกษา");

        jLabel34.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        jLabel34.setText("จบการศึกษาระดับ");

        jLabel35.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        jLabel35.setText("ชื่อสถานที่ที่จบการศึกษา");

        jLabel36.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        jLabel36.setText("วิชา/สาขาที่จบมา");

        jLabel37.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        jLabel37.setText("ประวัติการทำงาน");

        jLabel38.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        jLabel38.setText("ชื่อสำนักงาน");

        jLabel39.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        jLabel39.setText("ตำเเหน่ง");

        jLabel41.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        jLabel41.setText("ถึงวันที่");

        jLabel42.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        jLabel42.setText("เหตุผลที่ออก");

        jLabel43.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        jLabel43.setText("เหตุผลที่อยากมาทำงานที่นี่คืออะไร");

        first_name.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        age.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        ethnicity.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        nationality.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        religion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        birthday.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        id_card.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        current_address.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        district_1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        district_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                district_1ActionPerformed(evt);
            }
        });

        district_2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        phone_number.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        province.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        father_name.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        mother_name.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        father_age.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        father_age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                father_ageActionPerformed(evt);
            }
        });

        mother_age.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        father_ethnicity.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        mother_ethnicity.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        father_nationality.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        mother_nationality.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        husband_or_wife_name.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        husband_or_wife_age.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        father_occupation.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        mother_occupation.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        husband_or_wife_ethnicity.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        husband_or_wife_phone.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        husband_or_wife_nationality.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        husband_or_wife_occupation.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        husband_or_wife_occupation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                husband_or_wife_occupationActionPerformed(evt);
            }
        });

        husband_or_wife_workplace.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        husband_or_wife_workplace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                husband_or_wife_workplaceActionPerformed(evt);
            }
        });

        husband_or_wife_position.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        education_level.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        name_place_graduated.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        graduated_subject.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        work_history.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        office_name.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        old_position.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel44.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        jLabel44.setText("เริ่มทำงานตั้งเเต่วันที่");

        start.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        stop.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        reason_for_resignation.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        reason_for_wanting_to_work_here.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel40.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        jLabel40.setText("ตำเเหน่งงานที่มาสมัคร");

        button_register.setFont(new java.awt.Font("Leelawadee UI", 0, 24)); // NOI18N
        button_register.setForeground(new java.awt.Color(51, 255, 0));
        button_register.setText("Register");
        button_register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_registerMouseClicked(evt);
            }
        });
        button_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_registerActionPerformed(evt);
            }
        });

        jLabel45.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        jLabel45.setText("นามสกุล");

        last_name.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel23.setFont(new java.awt.Font("Leelawadee UI", 0, 18)); // NOI18N
        jLabel23.setText("ชื่อเล่นภาษาอังกฤษ");

        position.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Position", "IT", "CEO", "เลขานุการ", "พนักงาน", "พนักงานขนส่ง" }));
        position.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                positionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(jLabel32)
                .addGap(191, 191, 191)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mother_name))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(father_name)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mother_age, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mother_ethnicity))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(father_age, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(father_ethnicity, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel21))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(father_nationality, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(father_occupation, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(mother_nationality, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mother_occupation, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(423, 423, 423))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(husband_or_wife_name, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(husband_or_wife_age, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel27)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(husband_or_wife_ethnicity, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel31)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(husband_or_wife_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(119, 119, 119)
                                .addComponent(work_history, javax.swing.GroupLayout.PREFERRED_SIZE, 658, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel26)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(husband_or_wife_nationality, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel28)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(husband_or_wife_occupation, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel29)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(husband_or_wife_workplace, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel34)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(education_level, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel35)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(name_place_graduated, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel36)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(graduated_subject, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel30)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(husband_or_wife_position, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel33)
                            .addComponent(jLabel37)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel38)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(office_name, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel39)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(old_position, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel44)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(start, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel41)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(stop, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel42)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(reason_for_resignation))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel43)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(reason_for_wanting_to_work_here, javax.swing.GroupLayout.PREFERRED_SIZE, 975, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(39, 39, 39)
                                .addComponent(button_register, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(106, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(current_address, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(birthday, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(id_card, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel9)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(district_1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel10))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel3)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(ethnicity, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(nationality, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(religion, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(district_2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel12)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(phone_number, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel11)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(province, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(first_name, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel45)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(last_name, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel40)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(position, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nickname, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel32)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(first_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel40)
                                    .addComponent(jLabel45)
                                    .addComponent(last_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(position, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ethnicity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nationality, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(religion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(nickname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(birthday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(id_card, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(current_address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(district_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phone_number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(province, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(district_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(father_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(father_age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(father_ethnicity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(father_nationality, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(father_occupation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22)
                            .addComponent(mother_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mother_age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mother_ethnicity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mother_nationality, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mother_occupation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(button_register, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel25)
                                    .addComponent(jLabel27)
                                    .addComponent(jLabel31)
                                    .addComponent(husband_or_wife_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(husband_or_wife_age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(husband_or_wife_ethnicity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(husband_or_wife_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel26)
                                    .addComponent(jLabel28)
                                    .addComponent(jLabel29)
                                    .addComponent(husband_or_wife_nationality, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(husband_or_wife_occupation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(husband_or_wife_workplace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel30)
                                    .addComponent(husband_or_wife_position, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel33)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel34)
                                    .addComponent(jLabel35)
                                    .addComponent(jLabel36)
                                    .addComponent(education_level, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(name_place_graduated, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(graduated_subject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel37)
                                    .addComponent(work_history, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel38)
                                    .addComponent(jLabel39)
                                    .addComponent(jLabel41)
                                    .addComponent(office_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(old_position, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel44)
                                    .addComponent(start, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(stop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel42)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(reason_for_resignation, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel43)
                                    .addComponent(reason_for_wanting_to_work_here, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(106, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jfirstname_lastnameAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jfirstname_lastnameAncestorAdded
        // TODO add your handling code here:
        Connection c = null;
        Statement stmt = null;
        try {
            Class.forName("org.sqlite.JDBC");
            c = DriverManager.getConnection("jdbc:sqlite:database.db");
            c.setAutoCommit(false);
            stmt = c.createStatement();
            String a1 = user.getUser();
            ResultSet rs = stmt.executeQuery( "SELECT * FROM user_data WHERE username = '"+a1+"'" );
            String  first = rs.getString("first_name");
            String  last = rs.getString("last_name");
            jfirstname_lastname.setText(first + " " + last);
            rs.close();
            stmt.close();
            c.close();
        }
        catch ( Exception b ) {
            System.err.println( b.getClass().getName() + ": " + b.getMessage() );
            System.exit(0);
        }
    }//GEN-LAST:event_jfirstname_lastnameAncestorAdded

    private void jButtonlogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonlogoutMouseClicked
        // TODO add your handling code here:
        login_ui show = new login_ui();
        show.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonlogoutMouseClicked

    private void jBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBackMouseClicked
        // TODO add your handling code here:
        String a1 = user.getUser();
        String a2 = user.getFirst();
        All_Data account = new All_Data();
        account.setUser(a1);
        account.setFirst(a2);
        employee_history_ui employee_history = new employee_history_ui(account);
        employee_history.setVisible(true);
        dispose();
    }//GEN-LAST:event_jBackMouseClicked

    private void district_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_district_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_district_1ActionPerformed

    private void father_ageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_father_ageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_father_ageActionPerformed

    private void husband_or_wife_occupationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_husband_or_wife_occupationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_husband_or_wife_occupationActionPerformed

    private void husband_or_wife_workplaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_husband_or_wife_workplaceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_husband_or_wife_workplaceActionPerformed

    private void button_registerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_registerMouseClicked
        // TODO add your handling code here:
        Connection c = null;
        Statement stmt = null;
                try {
                    Class.forName("org.sqlite.JDBC");
                    c = DriverManager.getConnection("jdbc:sqlite:database.db");
                    c.setAutoCommit(false);
                    stmt = c.createStatement();
                    String a1 = first_name.getText();
                    String a2 = last_name.getText();
                    String a3 = position.getSelectedItem().toString();
                    String a4 = age.getText();
                    String a5 = ethnicity.getText();
                    String a6 = nationality.getText();
                    String a7 = religion.getText();
                    String a8 = birthday.getText();
                    String a9 = id_card.getText();
                    String a10 = current_address.getText();
                    String a11 = district_1.getText();
                    String a12 = district_2.getText();
                    String a13 = phone_number.getText();
                    String a14 = province.getText();
                    String a15 = father_name.getText();
                    String a16 = father_age.getText();
                    String a17 = father_ethnicity.getText();
                    String a18 = father_nationality.getText();
                    String a19 = father_occupation.getText();
                    String a20 = mother_name.getText();
                    String a21 = mother_age.getText();
                    String a22 = mother_ethnicity.getText();
                    String a23 = mother_nationality.getText();
                    String a24 = mother_occupation.getText();
                    String a25 = husband_or_wife_name.getText();
                    String a26 = husband_or_wife_age.getText();
                    String a27 = husband_or_wife_ethnicity.getText();
                    String a28 = husband_or_wife_phone.getText();
                    String a29 = husband_or_wife_nationality.getText();
                    String a30 = husband_or_wife_occupation.getText();
                    String a31 = husband_or_wife_workplace.getText();
                    String a32 = husband_or_wife_position.getText();
                    String a33 = education_level.getText();
                    String a34 = name_place_graduated.getText();
                    String a35 = graduated_subject.getText();
                    String a36 = work_history.getText();
                    String a37 = office_name.getText();
                    String a38 = old_position.getText();
                    String a39 = start.getText();
                    String a40 = stop.getText();
                    String a41 = reason_for_resignation.getText();
                    String a42 = reason_for_wanting_to_work_here.getText();
                    String a43 = getRandomNumberString();
                    String a44 = nickname.getText().toLowerCase();
                    ResultSet rs = stmt.executeQuery( "SELECT * FROM employee_data WHERE id_card = '"+a9+"'" );
                    String  first = rs.getString("first_name");
                    String  card = rs.getString("id_card");
                    ResultSet rs1 = stmt.executeQuery( "SELECT * FROM employee_data WHERE id_employee = '"+a43+"'" );
                    String  id_employ = rs1.getString("id_employee");
                     
                    while (a43.equals(id_employ)) {
                        a43 = getRandomNumberString();
                        if (!a43.equals(id_employ)) {
                             break;
                         }
                    }

                    if (a1.equals(first) && a9.equals(card)){
                        JOptionPane.showMessageDialog(null, "This person has already been registered.",
                        "ALERT", JOptionPane.WARNING_MESSAGE);
                    }
                    
                    else if (a1.equals(first) ){
                        JOptionPane.showMessageDialog(null, "This person has already been registered.",
                        "ALERT", JOptionPane.WARNING_MESSAGE);
                    }
                    
                    else if (a9.equals(card) ){
                        JOptionPane.showMessageDialog(null, "This id_card has already been registered.",
                        "ALERT", JOptionPane.WARNING_MESSAGE);
                    }
                    
                    else if (a3.equals("Select Position")){
                        JOptionPane.showMessageDialog(null, "Please select position.",
                        "ALERT", JOptionPane.WARNING_MESSAGE);
                    }
                    
                    else if (a1.equals(first) || a9.equals(card) || a1.equals("") || a2.equals("") || a3.equals("") || a4.equals("") || a5.equals("") || a6.equals("") || a7.equals("") || a8.equals("") || a9.equals("") || a10.equals("") || 
                            a11.equals("") || a12.equals("") || a13.equals("") || a14.equals("") || a15.equals("") || a16.equals("") || a17.equals("") || a18.equals("") || a19.equals("") || a20.equals("") || 
                            a21.equals("") || a22.equals("") || a23.equals("") || a24.equals("") || a25.equals("") || a26.equals("") || a27.equals("") || a28.equals("") || a29.equals("") || a30.equals("") || 
                            a31.equals("") || a32.equals("") || a33.equals("") || a34.equals("") || a35.equals("") || a36.equals("") || a37.equals("") || a38.equals("") || a39.equals("") || a40.equals("") || 
                            a41.equals("") || a42.equals("")){
                        JOptionPane.showMessageDialog(null, "Please fill in all the blanks.",
                        "ALERT", JOptionPane.WARNING_MESSAGE);
                    }
                    else if (!a1.equals(first) && !a9.equals(card) && !a1.equals("") && !a2.equals("") && !a3.equals("") && !a4.equals("") && !a5.equals("") && !a6.equals("") && !a7.equals("") && !a8.equals("") && !a9.equals("") && !a10.equals("") && 
                            !a11.equals("") && !a12.equals("") && !a13.equals("") && !a14.equals("") && !a15.equals("") && !a16.equals("") && !a17.equals("") && !a18.equals("") && !a19.equals("") && !a20.equals("") && 
                            !a21.equals("") && !a22.equals("") && !a23.equals("") && !a24.equals("") && !a25.equals("") && !a26.equals("") && !a27.equals("") && !a28.equals("") && !a29.equals("") && !a30.equals("") && 
                            !a31.equals("") && !a32.equals("") && !a33.equals("") && !a34.equals("") && !a35.equals("") && !a36.equals("") && !a37.equals("") && !a38.equals("") && !a39.equals("") && !a40.equals("") && 
                            !a41.equals("") && !a42.equals("")){
                        String sql = ("INSERT INTO employee_data(first_name,last_name,position,age,ethnicity,nationality,religion,birthday,id_card,current_address,district_1,district_2,"
                                + "phone_number,province,father_name,father_age,father_ethnicity,father_nationality,father_occupation,mother_name,mother_age,"
                                + "mother_ethnicity,mother_nationality,mother_occupation,husband_or_wife_name,husband_or_wife_age,"
                                + "husband_or_wife_ethnicity,husband_or_wife_phone,husband_or_wife_nationality,husband_or_wife_occupation,husband_or_wife_workplace,"
                                + "husband_or_wife_position,graduated_level,name_of_place_of_graduation,graduated_subject_or_field,work_history,office_name,"
                                + "old_position,start,stop,reason_for_resignation,reasons_for_wanting_to_work_here,id_employee,nick_name) VALUES('"+a1+"','"+a2+"','"+a3+"','"+a4+"','"+a5+"','"+a6+"',"
                                + "'"+a7+"','"+a8+"','"+a9+"','"+a10+"','"+a11+"','"+a12+"','"+a13+"','"+a14+"','"+a15+"','"+a16+"','"+a17+"','"+a18+"','"+a19+"','"+a20+"',"
                                + "'"+a21+"','"+a22+"','"+a23+"','"+a24+"','"+a25+"','"+a26+"','"+a27+"','"+a28+"','"+a29+"','"+a30+"','"+a31+"','"+a32+"','"+a33+"',"
                                + "'"+a34+"','"+a35+"','"+a36+"','"+a37+"','"+a38+"','"+a39+"','"+a40+"','"+a41+"','"+a42+"','"+a43+"','"+a44+"')"); 
                        stmt.executeUpdate(sql);
                        String randompassword = getRandomNumberString();
                        String sql1 = ("INSERT INTO user_data(username,password,first_name,last_name,position) VALUES('"+a44+"','"+randompassword+"','"+a1+"','"+a2+"','"+a3+"')");
                        stmt.executeUpdate(sql1);
                        JOptionPane.showMessageDialog(null, "Register Complete.",
                        "ALERT", JOptionPane.INFORMATION_MESSAGE);
                        String user1 = user.getUser();
                        String first1 = user.getFirst();
                        All_Data account = new All_Data();
                        account.setUser(user1);
                        account.setFirst(first1);
                        employee_history_ui employee_history = new employee_history_ui(account);
                        employee_history.setVisible(true);
                        dispose();
                        rs.close();
                        rs1.close();
                        stmt.close();
                        c.commit();
                    }
                } 
                catch ( Exception b ) {
                   if (c != null) {
                        try {
                            c.rollback();
                        } catch (Exception ex) {
                         }
                    }
                   System.err.println( b.getClass().getName() + ": " + b.getMessage() );
                }
                finally{
                    if (c != null) {
                        try {
                            c.close();
                        } catch (Exception ex) {
                        }
                }
                }
    }//GEN-LAST:event_button_registerMouseClicked

    private void button_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_registerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button_registerActionPerformed

    private void positionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_positionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_positionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(employee_new.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(employee_new.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(employee_new.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(employee_new.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new employee_new(new All_Data()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField age;
    private javax.swing.JTextField birthday;
    private javax.swing.JButton button_register;
    private javax.swing.ButtonGroup checkgroup_family_status;
    private javax.swing.ButtonGroup checkgroup_service;
    private javax.swing.JTextField current_address;
    private javax.swing.JTextField district_1;
    private javax.swing.JTextField district_2;
    private javax.swing.JTextField education_level;
    private javax.swing.JTextField ethnicity;
    private javax.swing.JTextField father_age;
    private javax.swing.JTextField father_ethnicity;
    private javax.swing.JTextField father_name;
    private javax.swing.JTextField father_nationality;
    private javax.swing.JTextField father_occupation;
    private javax.swing.JTextField first_name;
    private javax.swing.JTextField graduated_subject;
    private javax.swing.JTextField husband_or_wife_age;
    private javax.swing.JTextField husband_or_wife_ethnicity;
    private javax.swing.JTextField husband_or_wife_name;
    private javax.swing.JTextField husband_or_wife_nationality;
    private javax.swing.JTextField husband_or_wife_occupation;
    private javax.swing.JTextField husband_or_wife_phone;
    private javax.swing.JTextField husband_or_wife_position;
    private javax.swing.JTextField husband_or_wife_workplace;
    private javax.swing.JTextField id_card;
    private javax.swing.JLabel jBack;
    private javax.swing.JButton jButtonlogout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelDate;
    private javax.swing.JLabel jLabelProgram;
    private javax.swing.JLabel jLabelTime1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jfirstname_lastname;
    private javax.swing.JTextField last_name;
    private javax.swing.JTextField mother_age;
    private javax.swing.JTextField mother_ethnicity;
    private javax.swing.JTextField mother_name;
    private javax.swing.JTextField mother_nationality;
    private javax.swing.JTextField mother_occupation;
    private javax.swing.JTextField name_place_graduated;
    private javax.swing.JTextField nationality;
    private javax.swing.JTextField nickname;
    private javax.swing.JTextField office_name;
    private javax.swing.JTextField old_position;
    private javax.swing.JTextField phone_number;
    private javax.swing.JComboBox<String> position;
    private javax.swing.JTextField province;
    private javax.swing.JTextField reason_for_resignation;
    private javax.swing.JTextField reason_for_wanting_to_work_here;
    private javax.swing.JTextField religion;
    private javax.swing.JTextField start;
    private javax.swing.JTextField stop;
    private javax.swing.JTextField work_history;
    // End of variables declaration//GEN-END:variables
}
